### PR TITLE
Simplify if statement

### PR DESCRIPTION
**Pull request by beernjazz**
Hi,

This if statement can be simplified for php.

### CODE REVIEW

**Comment by mathiasverraes** [comment]
True, but it is not explicit that we specifically accept both.

**Comment by camspiers** [comment]
I don't think this should be changed. The existing code will give a much better error message in the case that you pass through something that `== 0`. The assertOperand function covers the type check.

As an example, if you pass through `false` with your code it will say 'Division by zero'.

**Comment by camspiers** [comment]
Here are some more examples:

```
cam-mbp:~ cam$ php -r "var_dump('' == 0);"
bool(true)
cam-mbp:~ cam$ php -r "var_dump(false == 0);"
bool(true)
cam-mbp:~ cam$ php -r "var_dump(null == 0);"
bool(true)
```

**Comment by camspiers** [comment]
The woes of type juggling

**Comment by camspiers** [comment]
@mathiasverraes I just noticed something that should be fixed though :). On line 232 we are still passing in `true` from when we used to pass in the division boolean.

```
$this->assertOperand($divisor, true);
```

**Pull request closed without merging**
