### PR TITLE
fix static calculator and some code style

### PR DESCRIPTION
**Pull request by piotrantosik**
Using static properties with eg. doctrine integration is not possible.
Some example: i use Money as embedded class and get it from entity. 
```php
$entity->getMoney()->greaterThanOrEqual($otherEntity->getMoney());
```
Currently it is impossible and generate fatal error because constructior is not triggered:
```php
Fatal error: Call to a member function compare() on null
```

### CODE REVIEW

**Comment by sagikazarmark** [comment]
I like the general idea, but I am unsure about instantiating a new calculator every time. Seems to be an overkill to me. How about falling back to static property in the non-static `getCalculator method`?

The object itself can still be stored in the money object, hence it will be the same reference.

I can imagine a static `globalCalculator` property and `getGlobalCalculator` methods.

What do you think?

**Comment by piotrantosik** [comment]
I agree that to return to the static - it is better performance.
Please recheck code and give me a feedback.

**Comment by sagikazarmark** [comment]
Sorry, I caused some confusion, I though you might want to keep the getCalculator method. If there is no separation, I think it is better to rename it back to calculator and getCalculator. Sorry about that.

I think the getCalculator does not have to be static, as we don't want to statically access it. The calculator property can and should be static.

:+1: Nice catch @piotrantosik

**Comment by piotrantosik** [comment]
Ok, soo now is:
- private static calculator property
- private methot to get this property

And looks good for me :smile:

**Comment by sagikazarmark** [comment]
LGTM, thank you.

**Pull request merged**
