### PR TITLE
updated currencies list according to http://openexchangerates.org/currencies.json

### PR DESCRIPTION
**Pull request by rgeraads**

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Thanks. Please note that this PR is against the current stable, but soon legacy version. See the nextrelease branch for the upcoming release.

**Comment by rgeraads** [comment]
Thank you for the heads-up! I will use the nextrelease branch.

**Comment by sagikazarmark** [comment]
Merging this into the legacy version.

**Comment by sagikazarmark** [comment]
Thanks @rgeraads

**Pull request merged**
