### PR TITLE
remove deprecated methods

### PR DESCRIPTION
**Pull request by frederikbosch**

### CODE REVIEW

**Comment by frederikbosch** [comment]
Travis suggests this PR contains errors, which it does not. Travis itself errors. I do not see any possibility to rerun the failed build.

**Comment by sagikazarmark** [comment]
The tests has an error:

https://travis-ci.org/mathiasverraes/money/jobs/102045637#L198

**Comment by frederikbosch** [comment]
@sagikazarmark I never saw `Error Output: stty: standard input: Inappropriate ioctl for device` as PHP error.

**Comment by sagikazarmark** [comment]
> Trying to @cover or @use not existing method "Money\CurrencyPair::getRatio"

There is an inappropriate annotation somewhere.

**Comment by frederikbosch** [comment]
@sagikazarmark Thanks, just learned something new!

**Comment by sagikazarmark** [comment]
:wink:

**Pull request merged**
